### ISSUE TITLE
Game over is not trivial

### ISSUE THREAD

**Issue by maximetinu** [Lifka/TetrisAllegroC-#5]
![tetrisgameoverisnottrivial](https://user-images.githubusercontent.com/16073309/27996895-e8e33ca8-64ec-11e7-97f9-db617f1c723a.jpg)
When the board is almost filled, near to the top,  it's possible for a new piece to be spawned in collision with others. What to do? Game over then? Avoid this kind of spawns? Translate the initial position?

Anyways, the standard gameover situation should be when any column of the first row in the board is full

**Comment by Lifka** [comment]
Done.
